/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INF;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author LUMINDA-PC
 */
public class main extends javax.swing.JFrame {
    GridBagLayout layout = new GridBagLayout();
    home p1;
    add_item p2;
    stock p3;
    sell p4;
    report p5;
    
    public main() {
        initComponents();
        
        
        p1 = new home();
        p2 = new add_item();
        p3 = new stock();
        p4 = new sell();
        p5 = new report();
       
        
        dynamic_panel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        dynamic_panel.add(p1,c);
        c.gridx=0;
        c.gridy=0;
        dynamic_panel.add(p2,c);
        dynamic_panel.add(p3,c);
        dynamic_panel.add(p4,c);
        dynamic_panel.add(p5,c);
        
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void time(){
  
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home_panel_1 = new javax.swing.JPanel();
        nenasala_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sidebar_panel = new javax.swing.JPanel();
        hide1 = new javax.swing.JLabel();
        button2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        button3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        button4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        button5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        button6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        button1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        sidebar_panel_hide = new javax.swing.JPanel();
        hide2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dynamic_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home_panel_1.setBackground(new java.awt.Color(255, 255, 255));
        home_panel_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nenasala_panel.setBackground(new java.awt.Color(0, 153, 51));
        nenasala_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/logout-32.png"))); // NOI18N
        jLabel2.setText("Logout?");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        nenasala_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Dream Lanka Stores...");
        nenasala_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 520, -1));

        home_panel_1.add(nenasala_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 1120, 60));

        sidebar_panel.setBackground(new java.awt.Color(0, 153, 51));
        sidebar_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/list-rich-32.png"))); // NOI18N
        hide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hide1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hide1MousePressed(evt);
            }
        });
        sidebar_panel.add(hide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 40, 40));

        button2.setBackground(new java.awt.Color(0, 153, 51));
        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button2MouseExited(evt);
            }
        });
        button2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/add-folder-32.png"))); // NOI18N
        jLabel3.setText("ADD ITEMS");
        button2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sidebar_panel.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 50));

        button3.setBackground(new java.awt.Color(0, 153, 51));
        button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button3MouseExited(evt);
            }
        });
        button3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/filled-box-32.png"))); // NOI18N
        jLabel1.setText("STOCK");
        button3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sidebar_panel.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 220, 50));

        button4.setBackground(new java.awt.Color(0, 153, 51));
        button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button4MouseExited(evt);
            }
        });
        button4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/sell-32.png"))); // NOI18N
        jLabel4.setText("SELL");
        button4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sidebar_panel.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 220, 50));

        button5.setBackground(new java.awt.Color(0, 153, 51));
        button5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button5MouseExited(evt);
            }
        });
        button5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/report-3-32.png"))); // NOI18N
        jLabel5.setText("REPORT");
        button5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sidebar_panel.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 220, 50));

        button6.setBackground(new java.awt.Color(0, 153, 51));
        button6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button6MouseExited(evt);
            }
        });
        button6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/settings-5-32.png"))); // NOI18N
        jLabel6.setText("SETTING");
        button6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sidebar_panel.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 220, 50));

        button1.setBackground(new java.awt.Color(0, 153, 51));
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                button1MouseReleased(evt);
            }
        });
        button1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/home-4-32.png"))); // NOI18N
        jLabel7.setText("HOME");
        button1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sidebar_panel.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/buy-128.png"))); // NOI18N
        sidebar_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 140));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        sidebar_panel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 200, 1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        sidebar_panel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 200, 1));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        sidebar_panel.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, 1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        sidebar_panel.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        sidebar_panel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 1));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        sidebar_panel.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 200, 1));

        home_panel_1.add(sidebar_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 780));

        sidebar_panel_hide.setBackground(new java.awt.Color(0, 153, 51));
        sidebar_panel_hide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/list-rich-32.png"))); // NOI18N
        hide2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hide2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hide2MousePressed(evt);
            }
        });
        sidebar_panel_hide.add(hide2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 40, 40));

        jLabel10.setFont(new java.awt.Font("Bauhaus 93", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("APPLICATIONS");
        sidebar_panel_hide.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 200, 60));

        jLabel11.setFont(new java.awt.Font("Bauhaus 93", 0, 55)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DESIGN");
        sidebar_panel_hide.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 190, 60));

        jLabel12.setFont(new java.awt.Font("Bauhaus 93", 0, 55)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("HIGH");
        sidebar_panel_hide.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 130, 60));

        jLabel13.setFont(new java.awt.Font("Bauhaus 93", 0, 55)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("AND");
        sidebar_panel_hide.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 110, 60));

        jLabel14.setBackground(new java.awt.Color(255, 255, 0));
        jLabel14.setFont(new java.awt.Font("Bauhaus 93", 0, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("QUALITY");
        sidebar_panel_hide.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 200, 60));

        jLabel15.setFont(new java.awt.Font("Bauhaus 93", 0, 40)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ASIAN JAVA");
        sidebar_panel_hide.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 60));

        jLabel16.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DEVELOPERS");
        sidebar_panel_hide.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 200, 60));

        jLabel17.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("DEVELOPING");
        sidebar_panel_hide.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 200, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        sidebar_panel_hide.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, 3));

        home_panel_1.add(sidebar_panel_hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 700));

        dynamic_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(dynamic_panel);

        home_panel_1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 1120, 640));

        getContentPane().add(home_panel_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int x=220;
    private void hide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide1MouseClicked
                       
        if(x==220){
            sidebar_panel.setSize(220,710);
            Thread th= new Thread(){
                @Override
                public void run(){
                    try {
                        for(int i = 220; i>=0; i--){
                            Thread.sleep(1);
                            sidebar_panel.setSize(i,710);
                        }
                    }
                    catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x=0;
        }
    }//GEN-LAST:event_hide1MouseClicked

    private void hide1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide1MousePressed

    }//GEN-LAST:event_hide1MousePressed

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseClicked
        button2.setBackground(Color.red);
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        
    }//GEN-LAST:event_button2MouseClicked

    private void button2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseEntered
        button2.setBackground(new Color(0,170,100));
        button1.setBackground(new Color(0,153,51));
        button3.setBackground(new Color(0,153,51));
        button4.setBackground(new Color(0,153,51));
        button6.setBackground(new Color(0,153,51));
        button5.setBackground(new Color(0,153,51));
    }//GEN-LAST:event_button2MouseEntered

    private void button2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseExited

    }//GEN-LAST:event_button2MouseExited

    private void button3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MouseClicked
        button3.setBackground(Color.red);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
        p5.setVisible(false);
       
    }//GEN-LAST:event_button3MouseClicked

    private void button3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MouseEntered
        button3.setBackground(new Color(0,170,100));
        button1.setBackground(new Color(0,153,51));
        button2.setBackground(new Color(0,153,51));
        button4.setBackground(new Color(0,153,51));
        button6.setBackground(new Color(0,153,51));
        button5.setBackground(new Color(0,153,51));

    }//GEN-LAST:event_button3MouseEntered

    private void button3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MouseExited

    }//GEN-LAST:event_button3MouseExited

    private void button4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MouseClicked
        button4.setBackground(Color.red);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
        p5.setVisible(false);
        
    }//GEN-LAST:event_button4MouseClicked

    private void button4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MouseEntered
        button4.setBackground(new Color(0,170,100));
        button1.setBackground(new Color(0,153,51));
        button2.setBackground(new Color(0,153,51));
        button3.setBackground(new Color(0,153,51));
        button6.setBackground(new Color(0,153,51));
        button5.setBackground(new Color(0,153,51));
    }//GEN-LAST:event_button4MouseEntered

    private void button4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MouseExited

    }//GEN-LAST:event_button4MouseExited

    private void button5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MouseClicked
        button5.setBackground(Color.red);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(true);
        
    }//GEN-LAST:event_button5MouseClicked

    private void button5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MouseEntered
        button5.setBackground(new Color(0,170,100));
        button1.setBackground(new Color(0,153,51));
        button2.setBackground(new Color(0,153,51));
        button3.setBackground(new Color(0,153,51));
        button6.setBackground(new Color(0,153,51));
        button4.setBackground(new Color(0,153,51));
    }//GEN-LAST:event_button5MouseEntered

    private void button5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MouseExited

    }//GEN-LAST:event_button5MouseExited

    private void button6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button6MouseClicked
        button6.setBackground(Color.red);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        
        this.dispose();
        register reg = new register();
        reg.setVisible(true);
        
    }//GEN-LAST:event_button6MouseClicked

    private void button6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button6MouseEntered
        button6.setBackground(new Color(0,170,100));
        button1.setBackground(new Color(0,153,51));
        button2.setBackground(new Color(0,153,51));
        button3.setBackground(new Color(0,153,51));
        button4.setBackground(new Color(0,153,51));
        button5.setBackground(new Color(0,153,51));
    }//GEN-LAST:event_button6MouseEntered

    private void button6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button6MouseExited

    }//GEN-LAST:event_button6MouseExited

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        button1.setBackground(Color.red);
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        
    }//GEN-LAST:event_button1MouseClicked

    private void button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseEntered
        button1.setBackground(new Color(0,170,100));
        button2.setBackground(new Color(0,153,51));
        button3.setBackground(new Color(0,153,51));
        button4.setBackground(new Color(0,153,51));
        button6.setBackground(new Color(0,153,51));
        button5.setBackground(new Color(0,153,51));
    }//GEN-LAST:event_button1MouseEntered

    private void button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseExited

    }//GEN-LAST:event_button1MouseExited

    private void button1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MousePressed

    }//GEN-LAST:event_button1MousePressed

    private void button1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseReleased

    }//GEN-LAST:event_button1MouseReleased

    private void hide2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide2MouseClicked
                 
        if(x==0){
            sidebar_panel.show();
            sidebar_panel.setSize(x,552);
            Thread th= new Thread(){
                @Override
                public void run(){
                    try {
                        for(int i = 0; i<=x; i++){
                            Thread.sleep(1);
                            sidebar_panel.setSize(i,710);
                        }
                    }
                    catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x=220;
        }
    }//GEN-LAST:event_hide2MouseClicked

    private void hide2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide2MousePressed

    }//GEN-LAST:event_hide2MousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       
    int check = JOptionPane.showConfirmDialog(null, "Do you want to delete");
       if(check ==0){
        try {
            login log=new login();
            log.setVisible(true);
            this.dispose();
            } catch (Exception e) {
                
            }
        } 
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel button1;
    private javax.swing.JPanel button2;
    private javax.swing.JPanel button3;
    private javax.swing.JPanel button4;
    private javax.swing.JPanel button5;
    private javax.swing.JPanel button6;
    private javax.swing.JPanel dynamic_panel;
    private javax.swing.JLabel hide1;
    private javax.swing.JLabel hide2;
    private javax.swing.JPanel home_panel_1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel nenasala_panel;
    private javax.swing.JPanel sidebar_panel;
    private javax.swing.JPanel sidebar_panel_hide;
    // End of variables declaration//GEN-END:variables
}
